export const slideData = [
    {
        id: 1,
        title: 'Chrismast Promo',
        thumb: 'image/thumbSale.jpg',
        image: 'image/BannerSale.jpg',
        desc: '',
        availability: '',
        price: '',
        oldPrice: '',
        newPrice: '',
        discount: '',
        button: 'Buy Now',
    },
    {
        id: 2,
        title: 'Black Myth Wukong',
        thumb: 'image/thumb1.jpg',
        image: 'image/Banner1.jpg',
        desc: 'Black Myth Wukong',
        availability: 'Availble',
        price: 'Rp. 699,999',
        oldPrice: '',
        newPrice: '',
        discount: '',
        button: 'Buy Now',
    },
    {
        id: 3,
        title: 'Stalker 2',
        thumb: 'image/thumb2.jpg',
        image: 'image/Banner2.jpg',
        desc: 'Stalker 2',
        availability: 'available',
        price: 'Rp. 665.000',
        oldPrice: '',
        newPrice: '',
        discount: '',
        button: 'Buy Now',
    },
    {
        id: 4,
        title: 'Fortnite',
        thumb: 'image/thumb3.jpg',
        image: 'image/Banner3.jpg',
        desc: 'Fortnite',
        availability: 'Avaible',
        price: '',
        oldPrice: '',
        newPrice: '',
        discount: '',
        button: 'Play For Free',
    },
    {
        id: 5,
        title: 'Alan Wake II',
        thumb: 'image/thumb4.jpg',
        image: 'image/Banner4.jpg',
        desc: 'Alan Wake II',
        availability: 'available',
        price: 'Rp. 285.250',
        oldPrice: 'Rp. 570.500',
        newPrice: '',
        discount: '50%',
        button: 'Buy Now',
    },
    {
        id: 6,
        title: 'EA Sports FC 25',
        thumb: 'image/thumb5.jpg',
        image: 'image/Banner5.jpg',
        desc: 'EA Sports FC 25',
        availability: 'available',
        price: 'Rp. 319.600',
        oldPrice: 'Rp. 799.000',
        newPrice: '',
        discount: '60%',
        button: 'Buy Now',
    },
]